### ISSUE TITLE
aws-load-balancer-controller installed through helm shows ImagePullBackOff

### ISSUE THREAD

**Issue by rojomisin** [kubernetes-sigs/aws-load-balancer-controller#1597] opened 2020-10-31 01:52 UTC
I deployed the new aws-load-balancer-controller to an aws EKS cluster via :
```
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"	
helm repo add eks https://aws.github.io/eks-charts	
helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
	--set clusterName=<cluster_name> \
  	--set serviceAccount.create=true \
  	--set serviceAccount.name=aws-load-balancer-controller \
  	--set autoDiscoverAwsRegion=true \
	--set autoDiscoverAwsVpcID=true \
  	-n kube-system
```

pod shows as unhealthy
```
$ kubectl get pods -A
NAMESPACE     NAME                                            READY   STATUS             RESTARTS   AGE
kube-system   aws-load-balancer-controller-6968fb7d67-25f6x   0/1     ImagePullBackOff   0          6m17s
...
```

```
kubectl get events -n kube-system
LAST SEEN   TYPE      REASON                 OBJECT                                               MESSAGE
<unknown>   Normal    Scheduled              pod/aws-load-balancer-controller-6968fb7d67-25f6x    Successfully assigned kube-system/aws-load-balancer-controller-6968fb7d67-25f6x to fargate-ip-10-55-190-10.us-west-2.compute.internal
7m3s        Normal    TaintManagerEviction   pod/aws-load-balancer-controller-6968fb7d67-25f6x    Cancelling deletion of Pod kube-system/aws-load-balancer-controller-6968fb7d67-25f6x
5m34s       Normal    Pulling                pod/aws-load-balancer-controller-6968fb7d67-25f6x    Pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0"
5m34s       Warning   Failed                 pod/aws-load-balancer-controller-6968fb7d67-25f6x    Failed to pull image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0": failed to resolve reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0": unexpected status code [manifests v2.0.0]: 401 Unauthorized
5m34s       Warning   Failed                 pod/aws-load-balancer-controller-6968fb7d67-25f6x    Error: ErrImagePull
5m21s       Normal    BackOff                pod/aws-load-balancer-controller-6968fb7d67-25f6x    Back-off pulling image "602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0"
119s        Warning   Failed                 pod/aws-load-balancer-controller-6968fb7d67-25f6x    Error: ImagePullBackOff

```

```
kubectl describe deployments.apps -n kube-system aws-load-balancer-controller 
Name:                   aws-load-balancer-controller
Namespace:              kube-system
CreationTimestamp:      Fri, 30 Oct 2020 18:19:03 -0700
Labels:                 app.kubernetes.io/instance=aws-load-balancer-controller
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=aws-load-balancer-controller
                        app.kubernetes.io/version=v2.0.0
                        helm.sh/chart=aws-load-balancer-controller-1.0.4
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: aws-load-balancer-controller
                        meta.helm.sh/release-namespace: kube-system
Selector:               app.kubernetes.io/instance=aws-load-balancer-controller,app.kubernetes.io/name=aws-load-balancer-controller
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=aws-load-balancer-controller
                    app.kubernetes.io/name=aws-load-balancer-controller
  Annotations:      prometheus.io/port: 8080
                    prometheus.io/scrape: true
  Service Account:  aws-load-balancer-controller
  Containers:
   aws-load-balancer-controller:
    Image:       602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0
    Ports:       9443/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /controller
    Args:
      --cluster-name=EKSCluster-c2YVz4RffA5S
      --ingress-class=alb
    Liveness:     http-get http://:61779/healthz delay=30s timeout=10s period=10s #success=1 #failure=2
    Environment:  <none>
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from cert (ro)
  Volumes:
   cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aws-load-balancer-tls
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   aws-load-balancer-controller-6968fb7d67 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  10m   deployment-controller  Scaled up replica set aws-load-balancer-controller-6968fb7d67 to 1
```

**Comment by kishorj** [comment] 2020-11-02 17:21
Could you check if the fargate pod execution role grants ECR access permissions? If the cluster were created by `eksctl --fargate` option, the IAM permissions should already be there -  https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html

**Comment by rojomisin** [comment] 2020-11-02 20:28
thanks @kishorj yes apparently i missed adding the managed policy `arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy`
```
  EKSPodsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks-fargate-pods.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
```

**Comment by fimbulvetr** [comment] 2020-11-02 20:29
There has been something that has changed. This is from my local machine, just attempting to reproduce:

```
fimbulvetr@ubuntu:~$ docker pull amazon/aws-alb-ingress-controller:v1.2.0-alpha.1
v1.2.0-alpha.1: Pulling from amazon/aws-alb-ingress-controller
1408b5006217: Pull complete 
9cdf569aa75c: Pull complete 
Digest: sha256:bd0ad42856eebdb6bbe4e7d1a19789c50af9b3d2f4e82b2f1fdd47e307afc1e8
Status: Downloaded newer image for amazon/aws-alb-ingress-controller:v1.2.0-alpha.1
docker.io/amazon/aws-alb-ingress-controller:v1.2.0-alpha.1

fimbulvetr@ubuntu:~$ docker pull amazon/aws-load-balancer-controller:v2.0.0
Error response from daemon: pull access denied for amazon/aws-load-balancer-controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

My `~/.docker/config.json` is empty. - long story short, the new ecr repo is requiring permission where the old one did not.

**Comment by kishorj** [comment] 2020-11-11 22:22
Closing the issue for now. If you have further questions feel free to reopen the issue.

**Closed** 2020-11-11 22:22 UTC

**Comment by christian1607** [comment] 2022-09-28 20:14
If you're working with S3 VPC endpoints, make sure to attach the correct policy because ECR under the hood  is a S3.
