### ISSUE TITLE
ALB Ingress Controller Reconciliation Slowness

### ISSUE THREAD

**Issue by niroowns** [kubernetes-sigs/aws-load-balancer-controller#1414] opened 2020-09-11 23:57 UTC
Hi,

We're noticing that new ingress resources can take up to 10-20 minutes sometimes to reconcile new ingress resources.  Most of these clusters have approximately ~25 existing ingresses that already exist.  Is it possible that increasing the worker threads of the controller would help to boost how fast reconciliation is occurring? I noticed there is an "undocumented" flag for this:  `--max-concurrent-reconciles`.  Not sure what ramifications if any, if we bump this past the default of 1?

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v1.1.9/internal/ingress/controller/config/config.go#L85

Thanks.

**Comment by niroowns** [comment] 2020-09-15 16:28
Tagging @M00nF1sh

**Comment by M00nF1sh** [comment] 2020-09-18 17:42
@niroowns 
Hi, Is there any logs in the controller, like some API got throttled? (increase the worker thread won't solve it).

10-20 minutes most likely caused by some error prevented the controller to create the infrastructure, and it backoff retries from 10ms to 16 minute. there should be logs in the controller pod.

**Comment by niroowns** [comment] 2020-09-18 18:59
> @niroowns
> Hi, Is there any logs in the controller, like some API got throttled? (increase the worker thread won't solve it).
> 
> 10-20 minutes most likely caused by some error prevented the controller to create the infrastructure, and it backoff retries from 10ms to 16 minute. there should be logs in the controller pod.

Hi - Just sent them over.  Hopefully they get sent your way.

**Comment by dabcoder** [comment] 2020-09-23 16:38
> We're noticing that new ingress resources can take up to 10-20 minutes sometimes to reconcile new ingress resources. Most of these clusters have approximately ~25 existing ingresses that already exist.

We're also noticing this issue with sometimes longer delays (for a similar number of ingresses). Curious to see if you've made any progress on this @niroowns?

**Comment by niroowns** [comment] 2020-09-24 22:14
> > We're noticing that new ingress resources can take up to 10-20 minutes sometimes to reconcile new ingress resources. Most of these clusters have approximately ~25 existing ingresses that already exist.
> 
> We're also noticing this issue with sometimes longer delays (for a similar number of ingresses). Curious to see if you've made any progress on this @niroowns (and have additional findings to share maybe)?

Hi @dabcoder - unfortunately not yet.  Will update back this thread once we make some progress.

**Comment by M00nF1sh** [comment] 2020-10-27 21:06
@niroowns @dabcoder 
Please try out our new v2.0.0 release, it dramatically improved the AWS API usage, which should solve this problem.

closing this, feel free to reopen if such issue exists in our v2.0.0 release.

**Closed by M00nF1sh** 2020-10-27 21:06 UTC
