### ISSUE TITLE
Reconciler error" "error"="failed to build LoadBalancer configuration due to unable to fetch subnets. Error: AuthFailure: AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by Tirano2150** [kubernetes-sigs/aws-load-balancer-controller#1534] opened 2020-10-22 14:23 UTC
I'm having an odd time out with the above error. I am using persistent AWS credentials for a user and a largely unmodified deployment file.

The ALB ingress controller will work when first created or if the alb-ingress-controller pod is deleted and automatically recreated, however it will stop working after a random length of time.

Is there any way I can get an aws sts get-caller-identity or any extra logs to find out what is causing this.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
 
            # ID of your cluster. Used when naming resources created
            # by the ALB Ingress Controller, providing distinction between
            # clusters.
            - --cluster-name={{ .Values.clusterName }}
 
            # AWS VPC ID this Ingress controller uses to create AWS resources.
            - --aws-vpc-id={{ .Values.awsVpcId }}
 
            # AWS region this Ingress controller operates in. Should match the region of your GKE on AWS cluster.
            - --aws-region={{ .Values.awsRegion }}
 
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
             secretKeyRef:
               name: alb-ingress-controller-creds
               key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: alb-ingress-controller-creds
                key: secret_access_key
 
          # Repository location of the ALB Ingress Controller.
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.8
      serviceAccountName: alb-ingress-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
      - pods/status
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller
subjects:
  - kind: ServiceAccount
    name: alb-ingress-controller
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
```

**Comment by M00nF1sh** [comment] 2020-10-22 16:26
Hi, 
did you try use the key/secret via AWS CLI to verify the credentials can work as intended

**Comment by Tirano2150** [comment] 2020-10-22 17:20
Hi,

I checked the key and it still works.
I mentioned in the original post that deleting the pod and allowing it to be recreated, which uses the same secret/creds,fixes the problems so it's not that.

I've seen the problem occur 3 times but only timed it once. It worked for about 14 hours after creation, but failed at around the 16 hour mark. Again, recreating the pod without changing anything else fixed the problem at that point.

**Comment by M00nF1sh** [comment] 2020-10-23 23:42
@Tirano2150 
would you help try our new released v2 to see if it have same issue? we haven't see issue like this reported.

**Comment by M00nF1sh** [comment] 2020-10-27 20:40
closing this. Feel free to reopen if this issue occurs in v2 as well

**Closed by M00nF1sh** 2020-10-27 20:40 UTC
