### ISSUE TITLE
[doc error] install crds

### ISSUE THREAD

**Issue by Hokwang** [kubernetes-sigs/aws-load-balancer-controller#3184] opened 2023-05-02 17:18 UTC
**Describe the bug**
In your doc, installation,
![image](https://user-images.githubusercontent.com/1247030/235737663-18890f06-93c8-4dd7-bdc7-a250560f02bf.png)

**Steps to reproduce**
that command occurs error.

```
kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
Alias tip: k apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
error: failed to run '/usr/local/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found
: exit status 128
```
**Expected outcome**
install crds

**Environment**

* AWS Load Balancer controller version
* Kubernetes version 1.24
* Using EKS (yes/no), if so version? yes

**Additional Context**:

**Comment by RyanRennCN** [comment] 2023-05-03 14:57
Adding for awareness, this is the same issue noted here:
https://github.com/aws/eks-charts/issues/939

**Comment by oliviassss** [comment] 2023-05-09 21:00
Thanks for the feedback, seems like the Github URL pattern has changed recently, we will review and update the doc.
/kind documentation

**Comment by oliviassss** [comment] 2023-05-10 22:27
@Hokwang I could not repro this issue, it could be a github transient issue, can you try again with the command?

**Comment by eweidner** [comment] 2023-05-12 17:38
@oliviassss I can confirm the issue still exists. I've been having this same issue for weeks. Luckily my current clusters have these already installed so I can comment out this step for upgrades. Still having this issue right now...

```
$ kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found
: exit status 128
```

**Comment by mhenson1** [comment] 2023-08-31 16:32
I didn't search adequately before creating my ticket and essentially created one for the same problem.
[Can't install TargetGroupBinding CRDs with k8s 1.28](https://github.com/aws/eks-charts/issues/994)

I was able to tie it to my client version of kubectl that I was running locally. If using 1.26 it worked, if I upgraded to 1.27 it didn't. As a workaround I had our automation pull down the crds.yaml file and apply it

wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
kubectl apply -f crds.yaml

**Comment by j3mdamas** [comment] 2023-10-03 13:53
Hi,

I also faced the same issue, but isn't it just a typo?

In the documentation, it's "github.com/aws/eks-charts/stable/aws-load-balancer-controller **//** crds?ref=master" while running with one forward slash works for me: "github.com/aws/eks-charts/stable/aws-load-balancer-controller **/** crds?ref=master"

**Comment by kasvith** [comment] 2023-10-05 17:46
i faced same issue today

**Comment by oliviassss** [comment] 2023-10-12 19:52
@j3mdamas, hi, neither of the links works for me, previously the older link works for me. I think it has something to do with the k8s version as @mhenson1 pointed out, I will update the doc

**Comment by oliviassss** [comment] 2023-10-13 23:12
Updated the doc to download the crds.yaml and then apply it. Closing this issue as for now, please feel free to reopen if there's any concern

**Closed by oliviassss** 2023-10-13 23:12 UTC
Labels: kind/documentation

**Comment by j3mdamas** [comment] 2023-10-17 15:04
> @j3mdamas, hi, neither of the links works for me, previously the older link works for me. I think it has something to do with the k8s version as @mhenson1 pointed out, I will update the doc

@oliviassss for me your fix seems fine. I just wanted to mention that it worked for me with the slash, and with the following version on kubectl:
> Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.28.2-eks-f8587cb

**Comment by yixuandang** [comment] 2024-02-13 03:44
> aws/eks-charts#939

Same issue here. 
╰─ kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"
error: failed to run '/usr/bin/git fetch --depth=1 https://github.com/aws/eks-charts/stable/aws-load-balancer-controller master': remote: Not Found
fatal: repository 'https://github.com/aws/eks-charts/stable/aws-load-balancer-controller/' not found
: exit status 128

**Comment by yixuandang** [comment] 2024-02-13 03:53
> https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml

single "/" worked for me somehow for kubectl 1.29. But I'm pretty sure on kubectl 1.23 I had double "/".

╰─ kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
customresourcedefinition.apiextensions.k8s.io/ingressclassparams.elbv2.k8s.aws created
customresourcedefinition.apiextensions.k8s.io/targetgroupbindings.elbv2.k8s.aws created
