### ISSUE TITLE
no identity-based policy allows the elasticloadbalancing:AddTags

### ISSUE THREAD

**Issue by dumlutimuralp** [kubernetes-sigs/aws-load-balancer-controller#3044] opened 2023-02-10 15:52 UTC
## Description

The current IAM policy published in the AWS Doc and AWS Load Balancer Controller GitHub page has incompatible definitions in it. This causes AWS Load Balancer Controller failing in provisioining an ELB due to some Addtag errors. Seems identical to [this previous GitHub issue](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/717).

## Versions

- Module Version [Required]:

- AWS Load Balancer controller 2.4.4 (also tested with 2.4.4)
- EKS v1.24 

## Reproduction Code [Required]

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: frontendnlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external #AWS Load Balancer Controller fulfills services that has this annotation 
    service.beta.kubernetes.io/aws-load-balancer-name : mynlb #User defined name given to AWS Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing #Places the load balancer on public subnets
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip #The Pod IPs should be used as the target IPs (rather than the node IPs as was the case with Network Load Balancer in the previous section)
  labels:
    app: frontendnlb
spec:
  type: LoadBalancer #The type of service
  ports:
    - port: 80 #The port which the service is running on
      targetPort: 9000 #The port on the pod which is backing this service. If not specified, it is assumed to be the same as the service port.
      name: http
  selector:
    app: frontend #The service identifies all the pods which have this label and then automatically configures the IP addresses of those pods as endpoints of this service.
EOF
```
## Expected behaviour

For AWS Load Balancer Controller to provision an NLB.

## Actual behaviour

No NLBs are provisioned. And AWS Load Balancer Controller generates the following error.

`{"level":"error","ts":1676040723.3378003,"logger":"controller.service","msg":"Reconciler error","name":"frontendnlb","namespace":"workshop","error":"AccessDenied: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/eksctl-mycluster-addon-iamserviceaccount-kub-Role1-ALZQNS3HQWFQ/1676040699752964147 is not authorized to perform: elasticloadbalancing:AddTags on resource: arn:aws:elasticloadbalancing:eu-west-2:578334270511:targetgroup/k8s-workshop-frontend-8a6a890206/* because no identity-based policy allows the elasticloadbalancing:AddTags action\n\tstatus code: 403, request id: 4ee09784-239c-4afb-94f1-958b50134d8c"}`

**Comment by dmegyesi** [comment] 2023-02-10 16:24
We just faced the exact same issue today, also on v2.4.4.

By removing this condition, the problem seems to be resolved: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/v2.4.4/docs/install/iam_policy.json#L160-L165

**Comment by abierbaum** [comment] 2023-02-10 16:37
I am running into this issue using AWS CDK to deploy an EKS stack with 

```
albController: {
   version: eks.AlbControllerVersion.V2_4_1,
},
```

**Comment by sjones512** [comment] 2023-02-10 17:23
duplicate of [https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692)?

**Comment by M00nF1sh** [comment] 2023-02-11 01:09
it's a duplicate of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692, which is caused by a IAM change in ELB for tag resource on creation. ELB team have already rollback their change. 

We'll sync with ELB team to update the IAM permission needed and update our default IAM policy.

**Comment by YikaiHu** [comment] 2023-06-19 08:30
For anyone who has encountered the same issue, we have found a solution in CDK.

Here is the solution,

The key to solving the problem is to explicitly declare the policy of the ALB controller and assign it when creating the cluster.

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692#issuecomment-1596743162

**Comment by armujahid** [comment] 2023-06-26 13:16
/remove-lifecycle rotten

I am facing this issue with aws-load-balancer-controller helm chart 1.4.8 v2.4.7 provisioned using v4.32.1 of https://github.com/aws-ia/terraform-aws-eks-blueprints

Ingress nginx failed to provision NLB because of this issue.

**Comment by justinlarose** [comment] 2023-07-25 23:58
This is fixed with this PR - https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3046/

**Closed** 2023-07-26 21:01 UTC
