### ISSUE TITLE
[v2] mutually exclusive rules are still created in 2.0.0.rcx7

### ISSUE THREAD

**Issue by runningman84** [kubernetes-sigs/aws-load-balancer-controller#1524] opened 2020-10-20 09:32 UTC
The alb ingress should not created two rules which are mutually exclusive...

In this case the alb ingress should throw an error.

sample ingress
```
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-health-alb
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  ports:
    - name: traefik
      port: 9000
      targetPort: traefik
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: wordpress
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=25,slow_start.duration_seconds=30
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: ingress-alb
  namespace: traefik
spec:
  rules:
  - host: alb.dev.mgmt.example.com
    http:
      paths:
      - backend:
          serviceName: traefik-health-alb
          servicePort: traefik
        path: /*
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: wordpress
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=25,slow_start.duration_seconds=30
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: ingress-alb2
  namespace: traefik
spec:
  rules:
  - host: alb.dev.mgmt.example.com
    http:
      paths:
      - backend:
          serviceName: traefik-health-alb
          servicePort: traefik
        path: /*
```

![image](https://user-images.githubusercontent.com/1699128/96567718-68255100-12c7-11eb-8fc8-7c7e1c94e3e9.png)

**Comment by M00nF1sh** [comment] 2020-10-21 13:11
@runningman84 
If i understand correctly, you configured two same rule, and you want to reduce the rules by remove the second rule.
In this version, we purposely only remove redundant rules if first rule is a redirect rule: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/main/pkg/ingress/rule_optimizer.go#L68

We have this behavior on purpose: `//  	(ideally this could applies to other action type as well, but we only consider redirect action for now`, we are tying to avoid unnecessary behavior change than old version in our first v2.0.0 release.
We can improve the rule optimization logic in future versions.

**Comment by runningman84** [comment] 2020-10-21 13:26
removes duplicates is a good idea (this should be an option which can be disabled and cause an error in case of duplicates), I am afraid that having two rules with different targets would cause a downtime...

**Comment by M00nF1sh** [comment] 2020-10-21 21:07
two rules won't cause downtime as the rule is evaluated in order, the first matched rule will get selected.

I'm not a fan of auto remove duplicates as well. (indeed we should have a flag for it). currently we have it for redirect rules to be backwards-compatible

**Comment by runningman84** [comment] 2020-10-22 05:22
I have this scenario in my mind, service a is deployed and serves live traffic. Some deploys another called service b with a new name but uses the name in ingress. Now live traffic might be served by service b which contains different content...

**Comment by M00nF1sh** [comment] 2020-10-22 16:34
@runningman84 Ingresses rule updates must be coordinated across users if it's in same ALB.
e.g. two unrelated rule can still conflicts for `img/apple/pics/product.png` depends on the order.
1. `/img/*/pics/*
2. `img/apple/*`

**Comment by runningman84** [comment] 2020-10-22 19:47
Ok I get that but multiple exactly equal rules can be detected...

**Comment by ChipWolf** [comment] 2020-10-24 14:40
This reads to me as intended behaviour. If you configure the same rule twice, you get the same rule twice, as AWS intended.
I don't think it should be up to the controller to do any additional validation to throw an error here, that's up to the AWS API.

**Comment by M00nF1sh** [comment] 2020-10-27 20:46
@ChipWolf 
Totally agree with u 👍 the controller shouldn't do things for user specified rules.

closing this, but feel free to reopen if we have further use cases.

**Closed by M00nF1sh** 2020-10-27 20:46 UTC
