### ISSUE TITLE
Delay between target removal in the TargetGroup and POD removal causing 502 error

### ISSUE THREAD

**Issue by maikobritzke** [kubernetes-sigs/aws-load-balancer-controller#3430] opened 2023-10-16 14:05 UTC
**Describe the bug**
I'm using HPA, and when the scalingdown is done, randomly the clients that consume the ALB receive a 502 error.

After much testing, I discovered that there is a delay between removing the POD (removing the internal IP) and removing the destination, within the TargetGroup, causing the ALB to still send traffic to a pod/port/ip that does not exist more. Even using a delay when closing the POD, this does not solve the problem.

I found some documentation and reports searching on the internet, but it actually seems to solve the problem.

Is there anything that helps me solve this problem?

**Environment**

* AWS Load Balancer controller version - 2.4.7
* Kubernetes version - 1.22 and 1.27
* Using EKS (yes/no), if so version? Yes, 1.22 and 1.27

**Comment by ptc-mrucci** [comment] 2024-03-27 11:09
Would recommend closing this issue as duplicate of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2366

**Closed** 2024-04-26 11:21 UTC
Labels: lifecycle/rotten
