### ISSUE TITLE
Existing targetgroupbinding cannot be patched

### ISSUE THREAD

**Issue by dai-mk** [kubernetes-sigs/aws-load-balancer-controller#2764] opened 2022-08-15 09:15 UTC
**Describe the bug**
Why is it that you can create and delete targetgroupbindings, but you can't modify an existing one. Use case is my targetgroup's name in AWS has changed I now want to update in Kubernetes.

**Steps to reproduce**
``` 
step 1:
have a targetgroupbinding created

step 2 type and change the targetgroup arn:
kubectl -n default edit targetgroupbinding mytargetgroup

step 3 get output
error: targetgroupbindings.elbv2.k8s.aws "mytargetgroup" could not be patched: admission webhook "vtargetgroupbinding.elbv2.k8s.aws" denied the request: TargetGroupBinding update may not change these fields: spec.targetGroupARN
````
**Expected outcome**
Targetgroupbinding can be always changed like other Kubernetes resources.

**Environment**

* AWS Load Balancer controller version: 1.4.2
* Kubernetes version: 1.22
* Using EKS (yes/no), if so version? 1.22

**Additional Context**:

**Comment by M00nF1sh** [comment] 2022-08-16 20:31
We explicitly to make targetGroupARN immutable to avoid dealing with edge cases/unclear semantic.
e.g. If we allow change targetGroupARN, we might have to clean targets from old targetGroup when changed.

such semantic exists in Kubernetes world as well, like pod resources including volume mounts are immutable, you need to delete and recreate for such scenario.

**Comment by kishorj** [comment] 2022-08-24 22:27
@dai-mk, I'm closing the issue since the targetGroupARN field is immutable as intended.

**Closed by kishorj** 2022-08-24 22:27 UTC
