### ISSUE TITLE
One instance of the NLB times out in one of the us-east-1 AZ

### ISSUE THREAD

**Issue by apryiomka** [kubernetes-sigs/aws-load-balancer-controller#1895] opened 2021-03-18 22:09 UTC
We created istio ingress gateway with NLB that looks like so:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: tls-ingressgateway
    istio: tls-ingressgateway
  name: tls-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    nodePort: 32150
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 30408
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 32381
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    nodePort: 30943
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: tls-ingressgateway
    istio: tls-ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: *******.elb.us-east-1.amazonaws.com
```

As the result, the `*******.elb.us-east-1.amazonaws.com` NLB is created in three availability zones resulting in 3 IPs the host resolves to. Now two IPs seems to be routing traffic just fine to the EKS LoadBalancer service, but one of the three for some reason doesn't route any traffic and constantly times out. I tried to delete the istio ingress LoadBalancer service and re-create, I get the same result back. Two out of three work, one doesn't. 

```
curl -v -HHost:httpbin.example.com "https://*******.elb.us-east-1.amazonaws.com/status/418" -k
*   Trying XXX.XXX.XXX.96...
* TCP_NODELAY set
* Connection failed
* connect to XXX.XXX.XXX.96 port 443 failed: Operation timed out
*   Trying XXX.XXX.XXX.27...
* TCP_NODELAY set
* Connected to *******.elb.us-east-1.amazonaws.com (XXX.XXX.XXX.27) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
```

Whenever NLB resolves to XXX.XXX.XXX.96 above, it would time out. If it resolves to the other two - XXX.XXX.XXX.27 or XXX.XXX.XXX.156, it works just fine. The IP addresses are set by AWS, not US, the AZs are also picked based on the subnets public subnets

**Comment by kishorj** [comment] 2021-03-19 17:22
@apryiomka, this looks like an issue on the NLB side. Please create a support case with the NLB team to investigate further.

**Comment by M00nF1sh** [comment] 2021-03-19 17:41
@apryiomka 
NLB behaves differently than alb. for NLB, cross-zone load balancing is disabled, which means the NLB nodes(IP returned by dns query) will only forward traffic to it's own zone and traffic will be dropped if there is no targets in that zone. 
Also, NLB will automatically remove nodes from DNS when the corresponding zone doesn't have targets, did you cached DNS results?

If that's causing your issue, you may consider enable cross-zone LB with annotation `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled`

**Comment by Nuru** [comment] 2021-03-28 03:46
I am wondering if this could be due to https://github.com/aws/amazon-vpc-cni-k8s/issues/1392

The prediction, if 1392 is the problem is that the destination IPs XXX.XXX.XXX.27 and XXX.XXX.XXX.156 are on the primary ENIs of the nodes (`eth0`) and the problem IP XXX.XXX.XXX.96 is on a secondary ENI (anything other than `eth0`). Does that fit?

**Comment by kishorj** [comment] 2021-06-02 22:24
@apryiomka, I'm closing this issue for now. If you still encounter this problem, feel free to reopen or create a new one.

**Closed by kishorj** 2021-06-02 22:24 UTC

**Comment by FalconerTC** [comment] 2023-05-25 11:33
Also seeing this problem now, exactly as described by OP (only using IP routing, not instance routing)

**Comment by tfpereira** [comment] 2023-05-25 11:53
iirc the issue on my end was related with not having cross zone load balancing enabled on the NLB - and since I had 3 AZs on the NLB but only 2 AZs in my cluster,  it would timeout whenever I'd hit the unmatched AZ. might not necessarily be your issue but worth looking into

**Comment by FalconerTC** [comment] 2023-05-25 12:39
My issue was this actually https://github.com/aws/amazon-vpc-cni-k8s/issues/1392 as linked above. Resolved by upgrading the VPC CNI in my cluster
