### ISSUE TITLE
ALB doesn´t find the subnets

### ISSUE THREAD

**Issue by tiagocborg** [kubernetes-sigs/aws-load-balancer-controller#1693] opened 2020-11-29 21:15 UTC
For some reason, the controller can´t find any subnet on my cluster, even with the proper tags. If I add the subnet annotation, it works fine. I have 3 subnets, pointing to the internet gateway and on different AZs.

Any hint on whats going on?
`{"level":"error","ts":1606683783.8805897,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"my-group-ingress","namespace":"","error":"cannot find at least two subnets from different Availability Zones, discovered subnetIDs: []"}`

![image](https://user-images.githubusercontent.com/6026596/100553827-4042e900-3288-11eb-820d-7c32c8fffd5d.png)

> annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
      alb.ingress.kubernetes.io/certificate-arn: -my cert arn-
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", 
  "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: my-group-ingress

**Comment by M00nF1sh** [comment] 2020-11-30 18:39
@tiagocborg 
Did the controller have correct `--cluster-name` flag set? it should be `eks-mycluster` in your case(which matches the `kubernetes.io/cluster/eks-mycluster` tag)

**Comment by fabiorauber** [comment] 2020-12-09 13:14
I'm experiencing the same problem in EKS cluster created by Rancher. After installing aws-load-balancer-controller, it outputs the following line repeatedly:
```
{"level":"error","ts":1607519227.999473,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"portalmodelo","namespace":"portalmodelo","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}
```
The subnets were created automatically by Rancher, and have the tags that are recommended by the docs at https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/subnet_discovery/:

```
kubernetes.io/cluster/portalmodelo | shared
kubernetes.io/role/elb | 1
```

**Comment by ttres** [comment] 2020-12-16 06:33
@tiagocborg and @fabiorauber , try to run this AWS CLI command and check it returns expected subnets (replace <clusterName> with real cluster name:

```
$ aws ec2 describe-subnets \
  --filters "Name=tag:kubernetes.io/cluster/<clusterName>,Values=shared" \
            "Name=tag:kubernetes.io/role/elb,Values=1"
```

If it don't return them, list all subnets for the cluster, and review tags don't have hidden chars:

```
$ aws ec2 describe-subnets \
  --filters "Name=tag:kubernetes.io/cluster/<clusterName>,Values=shared"
```

I've just fixed an issue like this caused by a dangling '\t' char. Add `--region <region>` to above commands if necessary.

**Comment by yanyixing** [comment] 2020-12-16 11:35
I also meet this issue in aws China

**Comment by tiagocborg** [comment] 2020-12-16 11:50
> @tiagocborg and @fabiorauber , try to run this AWS CLI command and check it returns expected subnets (replace with real cluster name:
> 
> ```
> $ aws ec2 describe-subnets \
>   --filters "Name=tag:kubernetes.io/cluster/<clusterName>,Values=shared" \
>             "Name=tag:kubernetes.io/role/elb,Values=1"
> ```
> 
> If it don't return them, list all subnets for the cluster, and review tags don't have hidden chars:
> 
> ```
> $ aws ec2 describe-subnets \
>   --filters "Name=tag:kubernetes.io/cluster/<clusterName>,Values=shared"
> ```
> 
> I've just fixed an issue like this caused by a dangling '\t' char. Add `--region <region>` to above commands if necessary.

thanks, @ttres.
I just did that, and my subnets were retrieved correctly. Although, I am not using the `shared` value, but `owned`

**Comment by fabiorauber** [comment] 2020-12-16 13:48
I second @tiagocborg's conclusion, and thanks for the tip @ttres. In my case, the subnets in my VPC were correctly retrieved by the first command above.

**Comment by moonape1226** [comment] 2020-12-25 03:00
I encountered the same problem as well, but it turned out that there was a mistake in my Helm configuration. I configured the `clusterName` with my cluster arn `arn:aws:eks:us-west-2:xxx:cluster/test-cluster`, but it should contain only cluster name `test-cluster`. Not sure if you are having the same issue.

**Comment by riponbanik** [comment] 2021-01-22 00:43
same to me not able to discover subnet, {"level":"error","ts":1611275327.654821,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"ingress-2048","namespace":"game-2048","error":"couldn't auto-discover subnets: unable to discover at least one subnet"}

**Comment by Nunuzac** [comment] 2021-01-22 16:26
I'm getting the same message "error":"couldn't auto-discover subnets: unable to discover at least one subnet" for private subnets, even tough when I run 

aws ec2 describe-subnets \
  --filters "Name=tag:kubernetes.io/cluster/<*cluster_name*>,Values=shared" \
                "Name=tag:kubernetes.io/role/internal-elb,Values=1"
 
it retrieves them correctly

**Comment by kishorj** [comment] 2021-02-17 04:18
closing the issue. Feel free to reopen or create a new one if issue persists.

**Closed by kishorj** 2021-02-17 04:18 UTC

**Comment by yanyixing** [comment] 2021-02-18 02:22
In aws China region, the service account's annotation must be set
`eks.amazonaws.com/audience: sts.amazonaws.com.cn`
