### ISSUE TITLE
Reaching `failed to introspect region from EC2Metadata...` on container start-up - vanilla EKS/Fargate

### ISSUE THREAD

**Issue by jellis** [kubernetes-sigs/aws-load-balancer-controller#1561] opened 2020-10-26 06:44 UTC
Mostly a smooth process to implement v2.0.0 of the load balancer controller.

On start-up of the aws-load-balancer-controller pod, however, I'm receiving the following error.

`{"level":"error","ts":1603693374.9411495,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}`

The image being used is `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller:v2.0.0`

Running on EKS 1.18 with Fargate profile in ap-southeast-2.

- Target group bindings applied (via github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master)
- `iamserviceaccount` configured, oidc configure (via https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json)
- `helm` used to install (via https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller)

**Comment by M00nF1sh** [comment] 2020-10-26 16:24
Hi, 
Did you specified `aws-region` and `aws-vpc-id` flag to the controller?

`--aws-region instead if EC2Metadata is unavailable:`
EC2Metadata is not available in fargate

**Comment by albertomiglionni** [comment] 2020-10-27 15:33
I'm using version 1.18 and I have the same problem:

{"level":"info","ts":1603812318.8614302,"msg":"version","GitVersion":"v2.0.0","GitCommit":"1028fa4f363a9a8e37b07ff6a093b7b422923512","BuildDate":"2020-10-21T22:17:18+0000"}
{"level":"error","ts":1603812325.139714,"logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to introspect region from EC2Metadata, specify --aws-region instead if EC2Metadata is unavailable: EC2MetadataRequestError: failed to get EC2 instance identity document\ncaused by: RequestError: send request failed\ncaused by: Get \"http://169.254.169.254/latest/dynamic/instance-identity/document\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller --set awsRegion=us-east-1 --set clusterName=xxxxxxxxxxxxxxxxxxxx --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller -n kube-system

**Comment by albertomiglionni** [comment] 2020-10-27 15:34
I installed EKS with fargate profile

**Comment by albertomiglionni** [comment] 2020-10-27 17:47
I changed the deployment as follows:

      containers:
        - args:
            - --cluster-name=a202606-mastersafdevops-eks-cluster
            - --ingress-class=alb
            - --aws-vpc-id=vpc-9c891dfa
            - --aws-region=us-east-1

**Comment by M00nF1sh** [comment] 2020-10-27 17:51
@albertomiglionni did it work? i assume it should

**Comment by albertomiglionni** [comment] 2020-10-27 17:56
In fact the error changed to:

{"level":"error","ts":1603820714.4299896,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"jenkins-ingress","namespace":"jenkins-qa-linux","error":"NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"}

I'm trying to resolve this error now

**Comment by M00nF1sh** [comment] 2020-10-27 18:17
@albertomiglionni 
it indicates either u disabled EC2MedataAccess or isn't configuring iamForServiceAccount correctly

**Comment by albertomiglionni** [comment] 2020-10-27 18:52
I entered the eks.amazonaws.com/role-arn: arn: aws: iam :: 980461583422: role / a202606-xxxxxxxxx-lab-eks-ingress anottation, but changed the error again.

{"level":"error","ts":1603824466.5774531,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"jenkins-ingress","namespace":"jenkins-qa-linux","error":"WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: 1f09f468-8b0a-494a-a842-705e2cf6ed87"}

**Comment by M00nF1sh** [comment] 2020-10-29 01:03
@albertomiglionni 
The trust policy on your role `arn: aws: iam :: xxxxxxxxxx: role / a202606-xxxxxxxxx-lab-eks-ingress` didn't allow the service account's credential to assume it.
Did you created above role and service account via eksctl?
If not, you should check our docs to setup trust policy correctly: https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html

**Comment by JoshSinghEscreen** [comment] 2020-10-29 18:16
Hello, I've having the same issue.  I was following https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html 

I'm a Kubernetes beginner so sorry for the elementary question.
How would i go about supplying the aws region and vpc id?

I tried:
```
 helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=<cluster-name> \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  **--set aws-region=us-west-1 --set aws-vpc-id=vpc#**-n kube-system
```

and still seeing this when doing `kubectl get pods --all-namespaces`
![image](https://user-images.githubusercontent.com/69487971/97614782-9b5a9500-19d7-11eb-8c15-988a905457ea.png)

**Comment by JoshSinghEscreen** [comment] 2020-10-29 18:47
**Update:**
Following guide:  https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html 
Seems setting region and vpcId works like this:
```
 helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=<cluster-name> \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  --set region=us-west-1 --set vpcId=<vpc#> -n kube-system
```

Sample application was accessible externally after that :D

**Comment by albertomiglionni** [comment] 2020-10-30 13:54
@M00nF1sh The error was resolved when I added the trusted relationship to the role.

{
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::XXXXXXXXXXX:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XXXXXX30BDC278BBD6C519F584592"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXX584592:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller"
        }
      }
    }

**Comment by kishorj** [comment] 2020-11-11 23:26
Closing the issue for now. If you have further questions feel free to reopen the issue.

**Closed** 2020-11-12 00:58 UTC

**Comment by applike-ss** [comment] 2024-08-22 06:58
This might also happen to you when upgrading to karpenter v1.0 due to a change in the node class which is setting the hop limit from 2 to 1, making all pods unable to reach the metadata service unless they use host networking. In this case you need to specify vpcId and region to make it not use imds.

**Comment by devopscaxsol** [comment] 2024-11-14 18:26
Hey All,

I have eks cluster setup using terraform. I am following below command for alb ingress installation,
```
eksctl create iamserviceaccount \
  --region xxxxxx \
  --name alb-ingress-controller \
  --namespace kube-system \
  --cluster edc-dev \
  --attach-policy-arn arn:aws:iam::xxxxx:policy/ALBIngressControllerPolicy \
  --approve \
  --override-existing-serviceaccounts

helm repo add eks https://aws.github.io/eks-charts
helm repo update

helm install alb-ingress-controller eks/aws-load-balancer-controller \
  --namespace kube-system \
  --set clusterName=xxxxx \
  --set serviceAccount.create=false \
  --set serviceAccount.name=alb-ingress-controller \
  --set ingressClass=alb \
  --set vpcID=vpc-xxxxx \
  --set region=eu-central-1

```
than 

I am facing ERROR like 
```
{"level":"error","ts":"2024-11-14T18:19:48Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to get VPC ID: failed to fetch VPC ID from instance metadata: error in fetching vpc id through ec2 metadata: get mac metadata: operation error ec2imds: GetMetadata, canceled, context deadline exceeded"}
```
Please suggest How to resolve this.

**Comment by applike-ss** [comment] 2024-11-15 07:00
@devopscaxsol You can always set the vpc id and region via the values, which i'd recommend if you are using e.g. Karpenter for instance scaling.

**Comment by moundekarpalay3** [comment] 2024-12-07 16:26
Hi @applike-ss  

I have created EKS using terraform but getting below error.


{"level":"info","ts":"2024-12-07T16:21:46Z","msg":"version","GitVersion":"v2.10.1","GitCommit":"2a63f05a5e0b73cf652b374ae0ae09220fa8b920","BuildDate":"2024-11-22T17:15:45+0000"}
{"level":"error","ts":"2024-12-07T16:21:51Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to get VPC ID: failed to fetch VPC ID from instance metadata: error in fetching vpc id through ec2 metadata: get mac metadata: operation error ec2imds: GetMetadata, canceled, context deadline exceeded"}

Pls let me know if you have solution.

**Comment by applike-ss** [comment] 2024-12-09 07:35
@moundekarpalay3 please take a look at the comment from @devopscaxsol (https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1561#issuecomment-2477129342)

**Comment by AlliotTech** [comment] 2024-12-30 10:23
> Hi @applike-ss
> 
> I have created EKS using terraform but getting below error.
> 
> {"level":"info","ts":"2024-12-07T16:21:46Z","msg":"version","GitVersion":"v2.10.1","GitCommit":"2a63f05a5e0b73cf652b374ae0ae09220fa8b920","BuildDate":"2024-11-22T17:15:45+0000"} {"level":"error","ts":"2024-12-07T16:21:51Z","logger":"setup","msg":"unable to initialize AWS cloud","error":"failed to get VPC ID: failed to fetch VPC ID from instance metadata: error in fetching vpc id through ec2 metadata: get mac metadata: operation error ec2imds: GetMetadata, canceled, context deadline exceeded"}
> 
> Pls let me know if you have solution.


Simply change the NodeGroup node metadata to optional:

<img width="571" alt="image" src="https://github.com/user-attachments/assets/ee6a5ae7-315f-43c6-9d92-6e223cf84fbe" />

**Comment by AlliotTech** [comment] 2024-12-30 10:25
Although this can simply solve the problem, the root cause of the issue may still in the incorrect policy configuration of this project, which by default cannot obtain metadata from IMDSv2.

**Comment by AmnehSalameh** [comment] 2025-01-10 14:12
> **Update:** Following guide: https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html Seems setting region and vpcId works like this:
> 
> ```
>  helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
>   --set clusterName=<cluster-name> \
>   --set serviceAccount.create=false \
>   --set serviceAccount.name=aws-load-balancer-controller \
>   --set region=us-west-1 --set vpcId=<vpc#> -n kube-system
> ```
> 
> Sample application was accessible externally after that :D

It took me hours and this makes it work as charm. Thanks

**Comment by ragboy** [comment] 2025-01-31 00:52
This was a pain, converting to automode. Not specifying the vpcId worked fine in Karpenter > 1, but when going to automode, I got this issue and resolved by specifying vpcId in chart values.

**Comment by clayg** [comment] 2025-02-12 02:54
Adding `--set=vpcId=vpc-xxxx` to my helm command worked for me as well

I don't really understand what this failure mode or this error message or why it wasn't required before or why it is now?

**Comment by wtchangdm** [comment] 2025-02-14 10:10
@clayg I just encountered this as well, and it was not required before. 

AWS load balancer controller v2.7.2
