### ISSUE TITLE
URL rewrite?

### ISSUE THREAD

**Issue by nowfox** [kubernetes-sigs/aws-load-balancer-controller#1268] opened 2020-05-20 02:53 UTC
I found this issues https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/835.
But the reply didn't solve the problem. The reply is to use redirect instead of rewrite.
In nginx ingress controller, the corresponding configuration is
`nginx.ingress.kubernetes .io/rewrite-target: /`

Assume the configuration is as follows
```
spec:
  rules:
    - http:
        paths:
          - path: /path1
            backend:
              serviceName: "service1"
              servicePort: 80
          - path: /paht2
            backend:
              serviceName: "service2"
              servicePort: 80
```
If the request URL is http://*.com/path1/abc.html , the expected result is that the backend service receives the request at abc.html Not path1/abc.html .
Do you have any idea?Thank you.

**Comment by BlackBsd** [comment] 2020-09-02 17:16
Any ideas on this issue?

**Comment by BlackBsd** [comment] 2020-10-03 12:22
The problem is still present

**Comment by bzumby** [comment] 2020-10-15 07:07
@M00nF1sh Please help people to get this clear. There are many of them who are waiting for these kind of rewrites with ALB Ingress Controller, and I believe, those people (i.e like our team) are using alternatives like Nginx Ingress Controller. 
So, to make this clear:
**Q**: Is this the limitation of ALB itself?
**A**: ?

**Comment by M00nF1sh** [comment] 2020-10-28 01:42
@bzumby Yes, it's the limitation of ALB itself, the controller cannot help until ALB itself supports request manipulation.

closing this and tracking in centralized ALB feature request itself: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571

**Closed by M00nF1sh** 2020-10-28 01:42 UTC
Labels: lifecycle/rotten
