### ISSUE TITLE
UnauthorizedOperation: You are not authorized to perform this operation

### ISSUE THREAD

**Issue by mkasinat** [kubernetes-sigs/aws-load-balancer-controller#2240] opened 2021-09-21 14:59 UTC
**Describe the bug**
A concise description of what the bug is.
I am trying to install the aws-load-balancer-controller V2.2.2 in my kubernetes cluster(v1.19) but after applied the kind ingress we are getting the below error message and it is not allowed to create an alb load balancer .
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedBuildModel  65s   ingress  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: bab9a6f3-88b9-4a70-a265-8c68d6a593d5
  Warning  FailedBuildModel  65s  ingress  Failed build model due to UnauthorizedOperation: You are not authorized to perform this operation.
           status code: 403, request id: b19e9271-2277-46d7-8ebe-9b7e8f73602d
**Steps to reproduce**
Please find the below links which we followed and trying to implement the alb ingress controller .
https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
Private Repo which i was referred .
https://github.com/RobinNagpal/kubernetes-tutorials/tree/master/06_tools/007_alb_ingress/01_eks
**Expected outcome**
A concise description of what you expected to happen.
It should allow the create a alb load balancer to route the traffic .
**Environment**
All the Environment
* AWS Load Balancer controller version v2.2.2
* Kubernetes version v1.19
* Using EKS (yes/no), if so version? Yes . eks.6

**Additional Context**:

**Comment by thanhma** [comment] 2021-09-21 15:07
@mkasinat 

Make sure the ServiceAccount used for aws-load-balancer-controller has correct IAM policy attached, and the policy has enough permissions.

I recommend you to double check this step from the Installation Guide:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/#setup-iam-role-for-service-accounts

**Comment by mkasinat** [comment] 2021-09-21 15:20
@thanhma We have tried the same steps without changing any order but we got the below error mesage.

{"level":"error","ts":1632237330.6128585,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"simple-ingress-8","namespace":"default","error":"UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: 2e212740-f1cb-492d-b23c-dd4a9e148896"}

we have created the kubernetes cluster via terraform include aws-alb-ingress-controller after that we followed the step which mentioned in the below url.

**Comment by kishorj** [comment] 2021-09-21 23:50
@mkasinat, did you configure IRSA?

**Comment by mkasinat** [comment] 2021-09-22 07:47
Hello, I am followed the below link and same step .

https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fkubernetes-sigs.github.io%2Faws-load-balancer-controller%2Fv2.2%2Fdeploy%2Finstallation%2F%23setup-iam-role-for-service-accounts&data=04%7C01%7Cmakeshkumar.kasinathan%40volvocars.com%7Cb327491176dc4ad675f308d97d118b8c%7C81fa766ea34948678bf4ab35e250a08f%7C0%7C0%7C637678336580880199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BL3VJrxLfV%2BuT83W9MbEtl2HRrPGhKbUASqgrK2XrJM%3D&reserved=0

But I have provisions the cluster via terraform for alb-ingress-controller with irsa but not for aws-load-balancer-controller. Please let me the step
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dectl** [comment] 2021-09-23 01:03
I'm having the same problem after updating to 2.2.4. Checked the IAM policy over and over, no luck.

**Comment by kishorj** [comment] 2021-09-24 20:59
If you've set IRSA, please verify the following

- check if your serviceaccount has the annotation
```
eks.amazonaws.com/role-arn: arn:aws:iam::xxxx:role/eksctl-<cluster>-addon-iamserviceaccount-kube-Role1-xxxx
```
  
- controller pod has the aws-iam-token volume
```
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
```

- and the mount
```
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
```

If you set IRSA after the controller pod, you will have to restart the lb controller deployment.

**Comment by apeschel** [comment] 2021-09-24 21:30
@kishorj Just checked, and IRSA isn't mentioned anywhere in the documentation, but it seems like the `eksctl utils associate-iam-oidc-provider` command enables it. If that's the case then we definitely have IRSA enabled, but are getting this error.

**Comment by apeschel** [comment] 2021-09-24 21:34
@kishorj  Following your guide, I see the following:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXX:role/eksctl-XXX
```

There are two controller pods running, is this correct?

Pod1

```
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
```

Pod2:

```
    volumes:
    - name: aws-iam-token
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```

```
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
```

It seems like everything matches your description, yet the problem persists.

**Comment by apeschel** [comment] 2021-09-24 21:39
@kishorj It looks like the IAM policy isn't getting attached to the IAM role used by the service account by following the guide.

**Comment by kishorj** [comment] 2021-09-24 21:50
IRSA => IAM Roles for ServiceAccounts
It is mentioned in the installation guide https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/. Note: If you use IRSA, and using helm chart, you'd need to pass the options `serviceAccount.create=false` and `serviceAccount.name=aws-load-balancer-controller`  during installation.

If the serviceaccount doesn't get updated by the `eksctl create  ` command, you will have to `eksctl delete iamserviceaccount` first and run the `eksctl create  ` again.

**Comment by apeschel** [comment] 2021-09-24 21:58
I don't see any explicit mention of IRSA in the installation guide though

![Screen Shot 2021-09-24 at 2 57 28 PM](https://user-images.githubusercontent.com/567739/134743888-19006f4e-8f56-4b93-b539-e99d0ccc17a1.png)

**Comment by apeschel** [comment] 2021-09-24 22:28
> If the serviceaccount doesn't get updated by the eksctl create command, you will have to eksctl delete iamserviceaccount first and run the eksctl create again.

I tried this, and it seemed to correctly attach the policy this time. However, I'm still getting errors:

```
Events:
  Type     Reason             Age    From     Message
  ----     ------             ----   ----     -------
  Warning  FailedDeployModel  2m45s  ingress  Failed deploy model due to RequestError: send request failed
caused by: Post "https://elasticloadbalancing.us-east-1.amazonaws.com/": dial tcp 10.0.1.146:443: i/o timeout
```

**Comment by apeschel** [comment] 2021-09-24 22:40
Is there some kind of DNS issue at play here?

From my local machine:

```
nc -tzv elasticloadbalancing.us-east-1.amazonaws.com 443
Warning: Inverse name lookup failed for `54.239.24.215'
elasticloadbalancing.us-east-1.amazonaws.com [54.239.24.215] 443 (https) open
```

```
dig +short elasticloadbalancing.us-east-1.amazonaws.com
elasticloadbalancing.amazonaws.com.
54.239.29.176
```

From a pod on the EKS cluster:

```
# nc -z -v -w 1 elasticloadbalancing.us-east-1.amazonaws.com 443
DNS fwd/rev mismatch: elasticloadbalancing.us-east-1.amazonaws.com != ip-10-0-3-151.ec2.internal
DNS fwd/rev mismatch: elasticloadbalancing.us-east-1.amazonaws.com != ip-10-0-1-146.ec2.internal
DNS fwd/rev mismatch: elasticloadbalancing.us-east-1.amazonaws.com != ip-10-0-2-254.ec2.internal
elasticloadbalancing.us-east-1.amazonaws.com [10.0.3.151] 443 (?) : Connection timed out
```

```
# getent hosts elasticloadbalancing.us-east-1.amazonaws.com
10.0.2.254      elasticloadbalancing.us-east-1.amazonaws.com
10.0.3.151      elasticloadbalancing.us-east-1.amazonaws.com
10.0.1.146      elasticloadbalancing.us-east-1.amazonaws.com
```

---

There's nothing special with the DNS for the cluster:

```
# cat /etc/resolv.conf
nameserver 172.20.0.10
search echoserver.svc.cluster.local svc.cluster.local cluster.local ec2.internal
options ndots:5
```

```
# dig elasticloadbalancing.us-east-1.amazonaws.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> elasticloadbalancing.us-east-1.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57852
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;elasticloadbalancing.us-east-1.amazonaws.com. IN A

;; ANSWER SECTION:
elasticloadbalancing.us-east-1.amazonaws.com. 30 IN A 10.0.3.151
elasticloadbalancing.us-east-1.amazonaws.com. 30 IN A 10.0.2.254
elasticloadbalancing.us-east-1.amazonaws.com. 30 IN A 10.0.1.146

;; Query time: 2 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; WHEN: Fri Sep 24 22:36:17 UTC 2021
;; MSG SIZE  rcvd: 253
```

```
# dig +short SOA elasticloadbalancing.us-east-1.amazonaws.com
ns-1536.awsdns-00.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400
```

**Comment by apeschel** [comment] 2021-09-27 17:01
So it turns out there were two overlapping issues at play here:

The first was the auth issue, which seems to have been caused by the IAM policy not getting attached to the IAM role used by the service account. There seems to be something wrong with the `eksctl create iamserviceaccount` that can cause this to happen without any warnings. Just deleting and recreating the IAM service account fixed the problem.

The second issue was someone on our side adding a conflicting elasticloadbalancing endpoint. Once I deleted that, everything worked correctly.

**Comment by mkasinat** [comment] 2021-09-27 17:04
Yes even my issue also got fixed after deleted the service and recreated again .
Additionally I have added the annotation for service account.
Now everything looks good.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kishorj** [comment] 2021-09-29 22:28
@mkasinat, I'm closing the issue. If you have further problems, please reopen or file a new issue.

**Closed by kishorj** 2021-09-29 22:28 UTC
