### ISSUE TITLE
NLB Attributes default value is not updated when unprovided

### ISSUE THREAD

**Issue by abebars** [kubernetes-sigs/aws-load-balancer-controller#2705] opened 2022-06-27 00:59 UTC
**Describe the bug**
If you change a default attribute value to another value and then remove the annotation, the value will not be reverted to the default value and will be ignored on the new update.

**Steps to reproduce**
- create an IP target group with an NLB without providing attribute values.
- preserve_client_ip is false for IP Mode by default.
- set `preserve_client_ip.enabled=true`
- the change will get applied as expected.
- remove the annotation from the service.
- the value will not change to the default value and will be ignored.
**Expected outcome**

The value should be updated to match the default settings if it's not provided.

**Environment**

* AWS Load Balancer controller version [2.4.1]
* Kubernetes version [1.22]
* Using EKS (yes/no), if so, version? [Yes]

**Additional Context**:

**Comment by kishorj** [comment] 2022-06-27 23:46
@abebars, if you don't explicitly configure an attribute value, the controller will ignore such attributes. If you previously configure an attribute, but remove from the annotation later, your AWS resource will continue to have the previous value. If you want a different value, you will need to modify the attribute value instead. This allows us to support out-of-band changes to the unmanaged attributes without the controller overwriting with default values.

**Comment by kishorj** [comment] 2022-08-09 21:55
@abebars, I'm closing the issue since this is the expected behavior.

**Closed by kishorj** 2022-08-09 21:55 UTC
