### ISSUE TITLE
Migrate to networking.k8s.io/v1 Ingress API

### ISSUE THREAD

**Issue by rifelpet** [kubernetes-sigs/aws-load-balancer-controller#2050] opened 2021-06-04 03:57 UTC
Kubernetes 1.22 will drop support for networking.k8s.io/v1beta1 which was introduced in Kubernetes 1.19.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

aws-load-balancer-controller still uses v1beta1:

https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/3a6ba6a7c16e5fe9f63949381b24cebadd7e8c9f/controllers/ingress/group_controller.go#L9

[Here](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-grid-scenario-service-account-iam/1400584492606820352/artifacts/cluster-info/kube-system/aws-load-balancer-controller-5df6665dbf-4fx9r/logs.txt) are pod logs from v2.2.0 running in a v1.22.0-alpha.2 cluster. The container fails to start due to networking.k8s.io/v1beta1 not being recognized.

In order to support Kubernetes 1.22, aws-load-balancer-controller will need to migrate to the networking.k8s.io/v1 Ingress API.

**Comment by M00nF1sh** [comment] 2021-07-14 22:16
/kind feature
We have been plan on this, the tricky part is that networking/v1 is not supported in 1.18, but 1.18 will still be supported by EKS when EKS announces support for 1.22.

So i think we'll need a way to dynamically discover the available Ingress versions and use networking/v1beta1 for v1.18 and translate it into networking/v1 from controller-side.

we'll figure this out before 1.22 is generally supported, If you have any thoughts in mind, feel free to raise a PR.

**Comment by olemarkus** [comment] 2021-07-15 18:56
This is a fairly common issue that we have seen on the kOps side for quite some time. We use k8s version to decide which version of an addon to install (by default).
I.e from our perspective, it is perfectly fine to drop 1.18 support for newer releases using networking/v1, and kOps will just deploy an older version on older k8s versions. Cluster Autoscaler would be the most well-known addon that even maintains one branch per k8s minor version.

Trying to discover which version of a resource and support all variation sounds like something that could become complicated over time.

**Comment by olemarkus** [comment] 2021-08-08 19:51
Any updates on this one now that 1.22 is out? We are looking to make all the kOps addons work for our stable release scheduled not too long from now.

**Comment by technotaff-nbs** [comment] 2021-10-01 00:56
This is causing us some grief, we are prepping all of our clusters for future releases and block most deprecated APIs.

Will this be fixed in 2.3?

**Comment by mycoditcodihub** [comment] 2021-10-31 19:34
Just ran into the same issue. Is there an update?

**Comment by ggermis** [comment] 2021-11-03 14:56
I wouldn't categorize this as a feature request anymore but a high priority issue since kubernetes has a stable 1.22 release since august 4th (almost 3 months). This is blocking anyone from upgrading (or even preparing to upgrade) their cluster

**Comment by mariomerco** [comment] 2021-11-03 15:15
> I wouldn't categorize this as a feature request anymore but a high priority issue since kubernetes has a stable 1.22 release since august 4th (almost 3 months). This is blocking anyone from upgrading (or even preparing to upgrade) their cluster

Same in here, this is blocking us to prepare ourselves to upgrade our EKS clusters whenever 1.22 comes available.

**Comment by lucazz** [comment] 2021-11-03 15:21
Same here, different stack but the same issue. 
This prevents us from rolling out newer versions of EKS clusters w/ terraform.

**Comment by BuffaloWill** [comment] 2021-11-08 16:59
Same here. This is a blocker for us as well.

**Comment by BrianKopp** [comment] 2021-11-19 00:57
This is handled OOTB in other mainstream helm charts, eg kube-prometheus-stack.

https://github.com/prometheus-community/helm-charts/blob/09b3de4d351d81841e0d5231dad184e2902ba64f/charts/kube-prometheus-stack/templates/prometheus/ingress.yaml#L9

And here

https://github.com/prometheus-community/helm-charts/blob/09b3de4d351d81841e0d5231dad184e2902ba64f/charts/kube-prometheus-stack/templates/_helpers.tpl#L138



Are you seeking something similar here for aws load balancer controller? Or are you moving forward with #2364?

**Comment by ggermis** [comment] 2021-11-19 08:32
@BrianKopp The issue is not the creation of the `Ingress` object with the v1 version, but that the aws-loadbalancer-controller looks for it using v1beta1

Code that looks for the ingress objects is at: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/controllers/ingress/group_controller.go#L224

The definition of `ingressResourcesGroupVersion` is at: https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/controllers/ingress/group_controller.go#L39

So while you can create an Ingress object with group `networking.k8s.io/v1` can be created, it will not be seen / picked u by the alb ingress controller who will only look for objects with group `networking.k8s.io/v1beta1`

**Comment by BrianKopp** [comment] 2021-11-19 11:53
Ah, thank you for that clarification! I totally misunderstood!

I see this being a feature tracked in 2.4.0. Is there already a WIP on these changes? Or are you seeking contributions?

**Comment by avivgold098** [comment] 2021-11-24 19:10
Thx for the update! 

Blocker for our organization upgrade to `1.22.*`

**Comment by seh** [comment] 2021-11-26 14:04
Is anyone working on fixing this, or is this project intending on hanging back at Kubernetes version 1.21? The "networking.k8s.io/v1" GV has been available for a year and a half—before [this project's first release using the new name](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.0.0).

**Comment by olemarkus** [comment] 2021-12-09 09:17
With 1.23 being out, users are now stuck two minor versions behind. K8s 1.21 is EOL as 1.24 is released in April, and users need time to upgrade before then as well.

**Comment by kishorj** [comment] 2021-12-09 15:45
We will move to the v1 apis for 2.4.0 and later releases. This issue is on the top of our list at the moment.

**Comment by sftim** [comment] 2021-12-21 09:36
If there's a related need to select a default version of the controller in its Helm chart, try something like:
```gotemplate
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
2.4.0
{{- else -}}
2.3.1
{{- end -}}
```
in a helper.

**Closed** 2022-01-05 20:53 UTC
Labels: kind/feature
