### ISSUE TITLE
couldn't auto-discover subnets - Unable to create Ingress

### ISSUE THREAD

**Issue by nsubrahm-aws** [kubernetes-sigs/aws-load-balancer-controller#2017] opened 2021-05-18 14:43 UTC
When I look into the logs of the controller pods, I see this message.

```bash
{"level":"error","ts":1621348446.8384569,"logger":"controller","msg":"Reconciler error","controller":"ingress","name":"eks-basic","namespace":"","error":"couldn't auto-discover subnets: UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: bdaab07d-ce75-4a92-a6ad-078118ab66e7"}
```

I don't know why `namespace` is `""` when I am creating the `Ingress` like so.

```bash
cat << EOF | kubectl -n eks-basic create -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: eks-basic
  name: eks-basic-orders
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: eks-basic
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  rules:
    - http:
        paths:
          - path: /eks-basic/orders
            backend:
              serviceName: eks-basic-orders
              servicePort: 80
EOF
```

Further, all worker nodes have the following policies.

- `AmazonEKSWorkerNodePolicy`
- `AmazonEC2ContainerRegistryReadOnly`
- `CloudWatchAgentServerPolicy`

The user creating the `Ingress` is same as the one who created the cluster; so, this user must have `system:masters` permissions. Why is this authorization error happening?

**Comment by nsubrahm-aws** [comment] 2021-05-18 14:51
I also checked the `sa/aws-load-balancer-controller` has `annotations.eks.amazonaws.com/role-arn` set to an IAM Role where the role does `Allow` for `ec2:DescribeSubnets` (amongst many others).

**Comment by jpaulodit** [comment] 2021-05-18 17:07
I had a similar error yesterday. Turns out my IAM policy for the controller was missing some more changes. This happened because I installed the controller with Helm which installed version 2.2.0.

But the AWS doc instruction [here](https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html) was referencing `curl -o v2_1_3_full.yaml https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.1.3/docs/install/v2_1_3_full.yaml` ( an older version )

**Comment by M00nF1sh** [comment] 2021-05-18 22:20
@nsubrahm-aws 
1. ```I don't know why namespace is "" when I am creating the Ingress like so.```. For this one, it's actually a non-issue. we implemented Ingress group as objects without namespaces. (so it's logged as namespace "", but the log message is from controller-runtime which we don't have control of)
2. would you run a amazonlinux2 pod with same sa, and exec into that pod and install awscli and execute `aws sts get-caller-identity`? wondering whether it could be caused by iam trust policies.

**Comment by chainhead** [comment] 2021-05-18 22:47
@jpaulodit so, the resolution is to _not_ use Helm?

@M00nF1sh that sounds similar to IAM policy difference as noted by @jpaulodit . Would you know if `2.2.0` uses/requires different IAM policies?

**Comment by jpaulodit** [comment] 2021-05-19 01:01
@chainhead You can use Helm. Double check the version of the controller that was installed, and match up with the right IAM policy version.

**Comment by chainhead** [comment] 2021-05-19 01:05
Thanks, @jpaulodit 

The latest update I have is this.

1. Use latest (`2.2.0`) as of typing this) policy JSON.
2. Launch with Helm.

I too had an earlier IAM policy document that caused this error.

**Comment by M00nF1sh** [comment] 2021-05-26 22:24
closing this issue. Feel free to reopen a new one if you encounter similar issue but not addressed with above comments 😄

**Closed** 2021-06-02 22:12 UTC
