### ISSUE TITLE
Ingress extension is deprecated 

### ISSUE THREAD

**Issue by chejuro1** [kubernetes-sigs/aws-load-balancer-controller#3038] opened 2023-02-08 17:25 UTC
W0208 17:14:34.247738       1 config.go:46] Environment variable configuration is deprecated, switch to the --aws-region flag.
W0208 17:14:34.248786       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
F0208 17:14:34.388214       1 main.go:107] no matches for kind "Ingress" in version "extensions/v1beta1"

**Comment by kishorj** [comment] 2023-02-08 18:02
duplicate of #3039, closing.

**Closed by kishorj** 2023-02-08 18:02 UTC
