### ISSUE TITLE
pod readiness gate performance is very poor

### ISSUE THREAD

**Issue by frankh** [kubernetes-sigs/aws-load-balancer-controller#3417] opened 2023-10-03 09:36 UTC
**Describe the bug**
With `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` our deployment that involves rolling out 100-300 pods consistently times out, instead of taking ~5mins for the pods to roll out it takes 20+mins

**Steps to reproduce**
enable `elbv2.k8s.aws/pod-readiness-gate-inject: enabled` and time a helm upgrade --wait with hundreds of pods in load balancers

**Expected outcome**
It should roll out relatively quickly

**Environment**

* AWS Load Balancer controller version: 2.6.1
* Kubernetes version: 1.27
* Using EKS (yes/no), if so version? yes, 1.27

**Additional Context**:
Most of the target group reconciliations get "requeued"

<img width="813" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2088870/64cc4248-4833-4b43-9361-70e7a4ec5865">

and only finish ~15mins later

<img width="573" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2088870/0e9c0853-5c32-4a95-a1f7-2df7433c5a55">

P99 reconciliation duration spikes

<img width="621" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2088870/5cbed5ba-2c7a-4750-9059-1c5cf75bc20f">

controller webhook rate:

<img width="309" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2088870/e85ef865-35fc-4ea8-bcaa-8ebdab36c227">

AWS API retries:

<img width="635" alt="image" src="https://github.com/kubernetes-sigs/aws-load-balancer-controller/assets/2088870/fdcc2568-572d-4baa-baa0-012d4941b705">

I tried setting EnableRGTAPI but it made no difference

**Comment by frankh** [comment] 2023-10-03 11:04
I think this may be a regression caused by https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/3373

I think the actual issue is pods are getting stuck and never having their readiness gate set once they are healthy. I rolled back to v2.6.0 and the issue is resolved

**Comment by M00nF1sh** [comment] 2023-10-04 22:10
@frankh 
With v2.6.1, the number of Pod patch request should be lesser than before and is expected to improve the performance.
I'm not able to reproduce this issue,  would you mind turn on '--log-level=debug` and share us the logs?

**Comment by oliviassss** [comment] 2023-10-30 22:48
@frankh, closing this issue for now, please feel free to reach out if there's any question, thanks.

**Closed by oliviassss** 2023-10-30 22:48 UTC
