### ISSUE TITLE
v2.1.2 - strange behaviour when deploying 2 ingress for the same service

### ISSUE THREAD

**Issue by blastik** [kubernetes-sigs/aws-load-balancer-controller#1928] opened 2021-04-15 11:44 UTC
hello,
we are using v2.1.2 of the controller and we have found a strange behaviour. I hope I can describe it clearly enough so you guys can understand and give us a hand (i will truly appreciate it).

we have a helm chart for our standard apps that creates among other stuff the following:
- 1 ingress with one host
- 1 deployment
- 1 service

we upgraded this helm chart to have the ability to create 2 ingress with one host each, pointing to the same service. one internal and one public. for that, we have had to obviously decouple the name of the ingress from `service-name` to `service-name-<public/private>`. here is the ingress object of the helm template:

```
{{- range .Values.ingress }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "app.conditionalTenancyName" $ }}-{{ .scheme }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "app.labels" $ | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: kubernetes.io/ingress-name={{ include "app.conditionalTenancyName" $ }},kubernetes.io/scheme={{ .scheme }},env={{ $.Values.app.environment }},environment={{ $.Values.app.environment }},datadog=enabled,owner={{ $.Values.app.team }}
    alb.ingress.kubernetes.io/scheme: {{ .scheme }}
    alb.ingress.kubernetes.io/actions.redirect-to-https: >
      {"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"}}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    {{- if .albLogs }}
    alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket={{ $.Values.app.environment }}-alb-accesslogs,access_logs.s3.prefix={{ include "app.conditionalTenancyName" $ }}-{{ .scheme }}
    {{- end }}
{{ toYaml .annotations | indent 4 }}
spec:
  rules:
  {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: redirect-to-https
              servicePort: use-annotation
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ include "app.fullname" $ }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}

```

here it comes the strange behaviour we saw.

1. first thing we see when we perform `helm upgrade` is that the old ALB is deleted from AWS **but not from k8s as ingress object**. which implies a downtime. the ingress controller is triggering  `Reconciler errors` `failed to delete securityGroup: timed out waiting for the condition`  
2. new ALBs (public and private) are deployed both to aws and k8s **but** we wanted to use the same `host` that the old single ingress had before for the public one. looks like this is not posible and we also have to decouple the `host` so everything works as expected with the dns resolution. we cannot use the old one!
3. the only way we could delete the old k8s ingress object manually is by removing the following

```
    finalizers:
    - ingress.k8s.aws/resources
 ```
probably we are getting a lot of things wrong but anyway...any thoughts ?

thank you!

**Comment by M00nF1sh** [comment] 2021-04-15 17:22
@blastik 
1. The ALB is tied to Ingress name. So if you changed the Ingress name, i.e. from `service-name` to `service-name-public`, the old ALB cannot be preserved. 
   * I'd suggest to leave the public one as "service-name", and private one as "service-name-private"
   * Another hacky approach(**note: this is not supported and implementation-specific and subject to change**) is to first scale down the controller to 0 replicas. Then manually adjust the AWS tag on every resource(LoadBalancer/TargetGroups/auto created securityGroup for LB) for old Ingress(service-name) from `ingress.k8s.aws/stack: <namespace>/service-name`   to `ingress.k8s.aws/stack: <namespace>/service-name-public`. Then do the helm upgrade and scale up the controller to 1 replicas(or more).

2. The reason that the old Ingress is not deleted could be caused by a known bug in security group handling: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1879. This can happen when you have some alive Ingress referencing non-exists services and the controller pod have restarted once. We have a fix merged but not released yet(which will be released in v2.2.0): https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1888

**Comment by blastik** [comment] 2021-04-20 08:29
thank you very much @M00nF1sh 

we ere expecting the ingress controller to be smart enough to create new ALB objects before deleting the old ones to avoid downtimes but looks like this is not the case. for instance, if you want to migrate an alb schema from internal to internet-facing or viceversa.

another thing we've noticed is that only modifying `alb.ingress.kubernetes.io/load-balancer-attributes` does not update the current ALB object either. for example to enable or disable access logs.

is this the expected behaviour ?

**Comment by M00nF1sh** [comment] 2021-04-20 20:13
@blastik 
we can indeed improve the ALB handling to create/configure new ALBs first. we deleted the old ALBs first to avoid naming conflicts as two ALB with same name is not allowed. (we could solve this by add all immutable attributes as part of naming generation algorithm).  However, since actions that result in ALB deletion is a disruptive action, and there is no time left to allow user adjust cnames before delete old ALBs, i don't think there can be much value added if we implemented it.

It's not expected behavior, modifying `alb.ingress.kubernetes.io/load-balancer-attributes` should work. One important note is that the V2 behaves a little differently than v1 for this annotation. In V2, there is no default value for individual attributes, remove an attribute from this annotation merely means "keep the attribute as it is currently on loadbalancer". So if you want to disable access logs or enable it, you should explicitly enable/disable via the annotation.

**Comment by blastik** [comment] 2021-04-22 07:17
@M00nF1sh 

regarding `alb.ingress.kubernetes.io/load-balancer-attributes` gotcha. thanks.

regarding the "feature request" to create a new ALB before deleting the old one I think it makes sense. naming issue can be overcame as you mention. regarding cnames adjustment, we use [external-dns ](https://github.com/kubernetes-sigs/external-dns) so we dont manually adjust any R53 record (if that's what you meant)

**Comment by M00nF1sh** [comment] 2021-04-28 22:17
@blastik 
I'll close this ticket as most of the issues here is answered 😄 

For the new ALB feature request, Would you mind to create a new dedicated feature request issue?

**Closed** 2021-04-28 22:19 UTC
