### ISSUE TITLE
No IP/Instances are registered in target group

### ISSUE THREAD

**Issue by ArchiFleKs** [kubernetes-sigs/aws-load-balancer-controller#2078] opened 2021-06-15 14:12 UTC
Suddently stopped working. Provisioning LB is working fine but IP target are no registered. I'm using 2.2.0.

The only thing that changed is that I updated my cluster form EKS 1.18 to 1.19

I have other cluster where registering target is working fine (either on 1.19 or 1.20).

Here load balancer is created but no target are registered

```
I0615 14:08:09.786968       1 trace.go:201] Trace[46243447]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125 (15-Jun-2021 14:07:00.785) (total time: 60001ms):
Trace[46243447]: [1m0.001387666s] [1m0.001387666s] END
E0615 14:08:09.787003       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 3417; INTERNAL_ERROR
I0615 14:10:08.144246       1 trace.go:201] Trace[1046338318]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125 (15-Jun-2021 14:09:00.142) (total time: 60001ms):
Trace[1046338318]: [1m0.001250325s] [1m0.001250325s] END
E0615 14:10:08.144278       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.Secret: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 3673; INTERNAL_ERROR
```

**Comment by M00nF1sh** [comment] 2021-06-16 22:06
I'm wondering whether there are some issues with EKS dataplane as the logs is `Failed to list *v1.Secret`.

Is there more logs? 
also, would you mind create a EKS support ticket? or share the clusterARN to us(yyyng AT amazon.com or joshikis AT amazon.com)

**Comment by ArchiFleKs** [comment] 2021-06-17 07:55
> joshikis AT amazon.com

Thanks I have contacted you and also opened a support ticket :)

**Comment by kishorj** [comment] 2021-06-30 22:15
@ArchiFleKs, @M00nF1sh responded back to your email. Could you confirm the issue is no longer there?

I'm closing the ticket for now. Feel free to reach out if you have further issues.

**Closed by kishorj** 2021-06-30 22:15 UTC
Labels: triage/needs-information

**Comment by shukla2009** [comment] 2021-09-24 04:03
What is the outcome suddenly start facing the same issue on EKS 1.18
