### ISSUE TITLE
Target Group Binding - Change Path in the health Check

### ISSUE THREAD

**Issue by quadrinho** [kubernetes-sigs/aws-load-balancer-controller#2933] opened 2022-12-16 12:59 UTC
**Describe the bug**
Hello,

we have create a Target Group Binding template to connect nginx service on an existing ALB:

`apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-ingress
spec:
  serviceRef:
    name: ingress-nginx-controller # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:eu-central-1:XXXXXX:targetgroup/tg-manual/531e601337226fdf`

But the path in the health check is /

Is it possible to configure the path of the health check?

**Steps to reproduce**

Use the above template for  Target Group Binding

**Expected outcome**
We need to change the path "/" in the health check section"

**Environment**

* AWS Load Balancer controller version  --> 1.4.4
* Kubernetes version --> 1.23
* Using EKS (yes/no), if so version?  --> yes  version 1.23

**Additional Context**:

**Comment by kishorj** [comment] 2022-12-16 17:21
@quadrinho, if you manually create target group binding, you can configure appropriate health check settings on the underlying target group - controller doesn't modify them.

**Comment by quadrinho** [comment] 2022-12-16 17:34
@kishorj thanks for the replying but i don't understand where i can configure the appropriate health check settings in the target group binding below:

```
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: tgb-ingress
spec:
  serviceRef:
    name: ingress-nginx-controller # route traffic to the awesome-service
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:eu-central-1:XXXXXXX:targetgroup/argocd2-manual/531e601337226fdf
```


Can you help me to understand better? Is there a section in the TargetGroupBinding where i can configure health check?

I didn't find it.

Thans a lot!

**Comment by kishorj** [comment] 2022-12-16 17:45
@quadrinho, in this case, you configure the health check settings from the AWS console for your target group ARN `arn:aws:elasticloadbalancing:eu-central-1:XXXXXXX:targetgroup/argocd2-manual/531e601337226fdf`.

**Comment by quadrinho** [comment] 2022-12-16 18:01
@kishorj  Thanks. Yes i can change it in the AWS Console.

I need to know if it is possible to configure it using the TargetGroupBinding Kubernetes object

Can anyone help me?

**Comment by kishorj** [comment] 2022-12-16 18:09
It is not possible using the TGB resources alone. If the controller managed the ALB/NLBs for ingress/service resources, then controller would also configure the health check settings based on the annotations.

**Comment by M00nF1sh** [comment] 2022-12-28 23:17
closing this as the issue is clear. TargetGroupBinding is designed to register/deregister targets only and won't touch targetGroup attributes.

**Closed by M00nF1sh** 2022-12-28 23:17 UTC
