### ISSUE TITLE
Setting the idle_timeout.timeout_seconds parameter does not work

### ISSUE THREAD

**Issue by mgledi** [kubernetes-sigs/aws-load-balancer-controller#3363] opened 2023-08-28 09:44 UTC
**Describe the bug**
Setting the idle_timeout.timeout_seconds parameter does not work. 

**Steps to reproduce**
We tried to update an existing alb first. 
We then tried to recreate an alb with the following attributes. 
```
...
ingressClassParams:
  create: true
  name: alb
  spec:
    group:
      name: common
    ipAddressType: dualstack
    loadBalancerAttributes:
    - key: idle_timeout.timeout_seconds
      value: "3600"
    scheme: internet-facing
    tags:
    - key: Environment
      value: ue2
    - key: Name
      value: dtmr-plat-ue2-dev
    - key: Namespace
      value: dtmr
    - key: Stage
      value: dev
    - key: Tenant
      value: plat
...
```

**Expected outcome**
The idle_timeout in the attributes tab when configuring EKS should contain 120s. 

**Environment**

* AWS Load Balancer controller version: 1.5.5
* Kubernetes version: 1.25
* Using EKS (yes/no), if so version? yes

**Additional Context**:
We are using cloudposse's component to manage EKS: 1.25

**Comment by jerryhe1999** [comment] 2023-08-28 19:24
Hi @mgledi, the ingressClass and its spec.loadBalancerAttribute are only supported for AWS LBC versions newer than v2.3. I don't think version v1.5.5 supports this feature.

**Comment by oliviassss** [comment] 2023-10-10 23:23
@mgledi, hi sorry for the late reply, but I couldn't reproduce this issue, I use your idle_timeout configuration on my ingress manifest, the ingressclassparam works as expected, the idle_timeout of the ALB attribute has been updated to 3600s. 
do you create an ingress class and specify it in the ingress manifest? Do you have spec.namespaceSelector in your ingressclassparam that restrict the ingresses that can specify the ingress class?

**Comment by oliviassss** [comment] 2023-10-30 22:58
Closing this issue for now, please feel free to reach out if there's any question, thanks.

**Closed by oliviassss** 2023-10-30 22:58 UTC
