### ISSUE TITLE
Application Load Balancer-type Target Group for Network Load Balancer

### ISSUE THREAD

**Issue by kakarotbyte** [kubernetes-sigs/aws-load-balancer-controller#2667] opened 2022-05-27 12:18 UTC
**Is your feature request related to a problem?**

**Describe the solution you'd like**
A description of what you want to happen.

- It will be great if Service type LoadBalancer (NLB ) is allowed to attach an external or ingress [ALB as Target](https://aws.amazon.com/blogs/networking-and-content-delivery/application-load-balancer-type-target-group-for-network-load-balancer/#:~:text=Today%2C%20we%20are%20launching%20ALB,manage%20changing%20ALB%20IP%20addresses.)

**Comment by phajduk** [comment] 2022-08-03 18:43
@kakarotbyte is it a dupe of https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2297 ?

**Comment by kakarotbyte** [comment] 2022-08-03 21:31
Yup oyu are correct  it is a duplicate

**Comment by kishorj** [comment] 2022-08-04 22:58
@kakarotbyte, closing the issue as duplicate.

**Closed by kishorj** 2022-08-04 22:58 UTC
